### ISSUE TITLE
[task]: record demo using asciinema

### ISSUE THREAD

**Issue by hexfusion** [hexfusion/avalanchego#5]
https://asciinema.org/

**Comment by ianjennings** [comment]
Hey @hexfusion, I'm from https://dashcam.io. We do logs + video similar to asciinema ([here's a demo](https://app.dashcam.io/replay/6495068a07fc9000623f3366?share=8ZC5p3O00vLrlgUSCqjcbg)). Would you want me to make demo video of avalanche with dashcam and make a pull request?
