### ISSUE TITLE
[task] create podman container client

### ISSUE THREAD

**Issue by hexfusion** [hexfusion/avalanchego#7]
podman go bindings allow us to create out own client with the basic functionality we need to communicate with our pods.

possible location
`avalanchego/vms/rpcchainvm/runtime/container/client`

Core Client Features in a possible order of priority

- `Pull` a container image
- `Start` a container
- `Stop` a container
- Check if container `Exists`.
- `Remove` a container
- `Wait` for a container to start
- `Inspect` a container

We can extend the demo and use the podman binding sna dimplementation as refernce.

- https://github.com/containers/podman/tree/main/pkg/bindings
- https://github.com/containers/podman/tree/main/cmd/podman
- https://github.com/containers/Demos/blob/main/podman_go_bindings
-

**Comment by exdx** [comment]
@hexfusion for the purposes of the demo do we really need all this functionality? Versus just using the `kube play` API to simply run the subnet pod on demand?

**Comment by hexfusion** [comment]
Yeah I think we can just wrap `PlayWithBody` with `Start` for example and  `DownWithBody` with `Stop`
